steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - 'https://github.com/qupath/qupath.git'
  - 'qupath'
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'checkout'
  - 'tags/v0.3.0'
  dir: 'qupath'
- name: 'maven:3.6.1-jdk-11'
  args:
  - 'mvn'
  - 'install'
